/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-02 04:50:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import modelo.Puesto;
import modelo.Empleado;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("modelo.Empleado");
    _jspx_imports_classes.add("modelo.Puesto");
    _jspx_imports_classes.add("javax.swing.table.DefaultTableModel");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Empleados</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h1>Formulario Empleados</h1>\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#modal_empleado\" onclick=\"limpiar()\">Nuevo</button>\n");
      out.write("        \n");
      out.write("        <div class=\"container\">\n");
      out.write("        <div class=\"modal\" id=\"modal_empleado\">\n");
      out.write("        <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("      \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!-- Modal body -->\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <form action=\"sr_empleado\" method=\"post\" class=\"form-group\">\n");
      out.write("        <label for=\"lbl_id\"><b>ID</b></label>\n");
      out.write("        <input type=\"text\" name=\"txt_id\" id=\"txt_id\" class=\"form-control\" value=\"0\" readonly>\n");
      out.write("        \n");
      out.write("        <label for=\"lbl_codigo\" class=\"form-label\"><b>Codigo</b></label>\n");
      out.write("        <input type=\"text\" name=\"txt_codigo\" id=\"txt_codigo\" class=\"form-control\" placeholder=\"Ejemplo: E001\" pattern=\"[E]{1}[0-9]{3}\" required>\n");
      out.write("        \n");
      out.write("        <label for=\"lbl_nombres\" class=\"form-label\"><b>Nombres</b></label>\n");
      out.write("        <input type=\"text\" name=\"txt_nombres\" id=\"txt_nombres\" class=\"form-control\" placeholder=\"Ejemplo: Nombre 1 Nombre 2\" required> <!-- Corregido el ID a \"txt_nombres\" -->\n");
      out.write("        \n");
      out.write("        <label for=\"lbl_apellidos\" class=\"form-label\"><b>Apellidos</b></label>\n");
      out.write("        <input type=\"text\" name=\"txt_apellidos\" id=\"txt_apellidos\" class=\"form-control\" placeholder=\"Ejemplo: Apellido 1 Apellido 2\" required> <!-- Corregido el ID a \"txt_apellidos\" -->\n");
      out.write("        \n");
      out.write("        <label for=\"lbl_direccion\" class=\"form-label\"><b>Direccion</b></label>\n");
      out.write("        <input type=\"text\" name=\"txt_direccion\" id=\"txt_direccion\" class=\"form-control\" placeholder=\"No. Casa, Calle, Zona, Ciudad\" required>\n");
      out.write("        \n");
      out.write("        <label for=\"lbl_telefono\" class=\"form-label\"><b>Telefono</b></label>\n");
      out.write("        <input type=\"number\" name=\"txt_telefono\" id=\"txt_telefono\" class=\"form-control\" placeholder=\"Ejemplo: 14151214\" required>\n");
      out.write("        \n");
      out.write("        <label for=\"lbl_fn\" class=\"form-label\"><b>Nacimiento</b></label>\n");
      out.write("        <input type=\"date\" name=\"txt_fn\" id=\"txt_fn\" class=\"form-control\" required>\n");
      out.write("        \n");
      out.write("        <label for=\"lbl_puesto\"><b>Puesto</b></label>\n");
      out.write("        <select name=\"drop_puesto\" id=\"drop_puesto\" class=\"form-control\">\n");
      out.write("              \n");
      out.write("            ");

                   Puesto puesto = new Puesto();
                    HashMap<String,String> drop = puesto.drop_sangre();
                    for (String i: drop.keySet()){
                   out.println("<option value='" + i + "' >" + drop.get(i) + "</option>");
                   }
               
      out.write("\n");
      out.write("               \n");
      out.write("            </select>\n");
      out.write("            <br>\n");
      out.write("            <button name=\"btn_agregar\" id=\"btn_agregar\" value=\"agregar\" class=\"btn btn-primary btn-lg\">Agregar</button>\n");
      out.write("            <button name=\"btn_modificar\" id=\"btn_modificar\" value=\"modificar\" class=\"btn btn-success btn-lg\">Modificar</button>\n");
      out.write("            <button name=\"btn_eliminar\" id=\"btn_eliminar\" value=\"eliminar\" class=\"btn btn-danger btn-lg\"  onclick=\"javascript:if(!confirm('¿Desea Eliminar?'))return false\">Eliminar</button>        \n");
      out.write("          <button type=\"button\" class=\"btn btn-danger btn-lg\" data-dismiss=\"modal\">Cerrar</button>  \n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div> \n");
      out.write("            \n");
      out.write("        \n");
      out.write("      \n");
      out.write("            <table class=\"table table-striped\">\n");
      out.write("            <thead>\n");
      out.write("            <tr>\n");
      out.write("            <th>Codigo</th>\n");
      out.write("            <th>Nombres</th>\n");
      out.write("            <th>Apellidos</th>\n");
      out.write("            <th>Direccion</th>\n");
      out.write("            <th>Telefono</th>\n");
      out.write("            <th>Nacimiento</th>\n");
      out.write("            <th>Puesto</th>\n");
      out.write("            </tr>\n");
      out.write("            </thead>\n");
      out.write("            \n");
      out.write("    <tbody id=\"tbl_empleados\">\n");
      out.write("        \n");
      out.write("      ");

          Empleado empleado = new Empleado();
              DefaultTableModel tabla = new DefaultTableModel();
              tabla = empleado.leer();
              for (int t=0;t<tabla.getRowCount();t++) {
              out.println("<tr data-id=" + tabla.getValueAt(t, 0) + " data-id_p=" + tabla.getValueAt(t,8) + ">");
              out.println("<td>" + tabla.getValueAt(t,1) + "</td>");
              out.println("<td>" + tabla.getValueAt(t,2) + "</td>");
              out.println("<td>" + tabla.getValueAt(t,3) + "</td>");
              out.println("<td>" + tabla.getValueAt(t,4) + "</td>");
              out.println("<td>" + tabla.getValueAt(t,5) + "</td>");
              out.println("<td>" + tabla.getValueAt(t,6) + "</td>");
              out.println("<td>" + tabla.getValueAt(t,7) + "</td>");
              out.println("</tr>");
          }
          
      out.write("\n");
      out.write("          \n");
      out.write("    </tbody>\n");
      out.write("    </table>\n");
      out.write("               \n");
      out.write("        </div>\n");
      out.write("                \n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js\" integrity=\"sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            function limpiar(){\n");
      out.write("            $(\"#txt_id\").val(0);\n");
      out.write("            $(\"#txt_codigo\").val('');\n");
      out.write("            $(\"#txt_nombres\").val(''); \n");
      out.write("            $(\"#txt_apellidos\").val(''); \n");
      out.write("            $(\"#txt_direccion\").val('');\n");
      out.write("            $(\"#txt_telefono\").val('');\n");
      out.write("            $(\"#txt_fn\").val('');\n");
      out.write("            $(\"#drop_puesto\").val(1);    \n");
      out.write("                \n");
      out.write("            };\n");
      out.write("            \n");
      out.write("            $('#tbl_empleados').on('click', 'tr td', function(event) {\n");
      out.write("            var target, id, codigo, nombres, apellidos, direccion, telefono, nacimiento, id_p;\n");
      out.write("            \n");
      out.write("            target = $(event.target);\n");
      out.write("            id = target.parent().data('id');\n");
      out.write("            codigo = target.parent(\"tr\").find(\"td\").eq(0).html();\n");
      out.write("            nombres = target.parent(\"tr\").find(\"td\").eq(1).html(); \n");
      out.write("            apellidos = target.parent(\"tr\").find(\"td\").eq(2).html(); \n");
      out.write("            direccion = target.parent(\"tr\").find(\"td\").eq(3).html();\n");
      out.write("            telefono = target.parent(\"tr\").find(\"td\").eq(4).html();\n");
      out.write("            nacimiento = target.parent(\"tr\").find(\"td\").eq(5).html();\n");
      out.write("            id_p = target.parent().data('id_p');\n");
      out.write("\n");
      out.write("            $(\"#txt_id\").val(id);\n");
      out.write("            $(\"#txt_codigo\").val(codigo);\n");
      out.write("            $(\"#txt_nombres\").val(nombres); \n");
      out.write("            $(\"#txt_apellidos\").val(apellidos); \n");
      out.write("            $(\"#txt_direccion\").val(direccion);\n");
      out.write("            $(\"#txt_telefono\").val(telefono);\n");
      out.write("            $(\"#txt_fn\").val(nacimiento);\n");
      out.write("            $(\"#drop_puesto\").val(id_p);\n");
      out.write("            $(\"#modal_empleado\").modal('show');\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            </script>\n");
      out.write("        \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
