/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-02 00:17:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Modelo_compras.Compras;
import Modelo_compras.Proveedor;
import Modelo_compras.Marca;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

public final class Registro_005fcompras_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("Modelo_compras.Marca");
    _jspx_imports_classes.add("javax.swing.table.DefaultTableModel");
    _jspx_imports_classes.add("Modelo_compras.Compras");
    _jspx_imports_classes.add("Modelo_compras.Proveedor");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <br>\n");
      out.write("        <h1 style=\"text-align: center;\">Mantenimiento Compras</h1>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("\n");
      out.write("<div class=\"d-flex justify-content-center\">\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#modal_nueva_compra\">\n");
      out.write("        Compra Nueva\n");
      out.write("    </button>\n");
      out.write("</div>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("        \n");
      out.write("<div class=\"modal fade\" id=\"modal_nueva_compra\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h5 class=\"modal-title\" id=\"exampleModalLabel\">Nueva Compra</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <form action=\"sr_cCompras?menu=Nueva_compra\" method=\"post\">\n");
      out.write("                    <!-- ID de Compra -->\n");
      out.write("                    \n");
      out.write("                        <div class=\"form-group mb-3\">\n");
      out.write("                            <label for=\"txt_id_compra\"><b>Código de Compra:</b></label>\n");
      out.write("                            <input type=\"text\" name=\"txt_id_compra\" id=\"txt_id_compra\" class=\"form-control\" value=\"\" readonly>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group mb-3\">\n");
      out.write("                            <label for=\"txt_noc\"><b>Orden de Compra:</b></label>\n");
      out.write("                            <input type=\"text\" name=\"txt_noc\" id=\"txt_noc\" class=\"form-control\" value=\"\" readonly>\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("\n");
      out.write("                    <!-- Proveedor -->\n");
      out.write("                    <div class=\"form-group mb-3\">\n");
      out.write("                            <label for=\"txt_id_proveedor\"><b>Proveedor: </b><a href=\"Registro_proveedor.jsp\">Ir a proveedores</a></label> \n");
      out.write("                            <select name=\"txt_id_proveedor\" id=\"txt_id_proveedor\" class=\"form-control\" required>\n");
      out.write("                                ");
 
                                    Proveedor proveedor = new Proveedor();
                                    DefaultTableModel tablaProveedores = proveedor.leer();
                                    for (int t = 0; t < tablaProveedores.getRowCount(); t++) {
                                        out.println("<option value='" + tablaProveedores.getValueAt(t, 0) + "'>" + tablaProveedores.getValueAt(t, 1) + "</option>");
                                    }
                                
      out.write("\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group mb-3\">\n");
      out.write("                            <label for=\"txt_fecha_orden\"><b>Fecha de Orden:</b></label>\n");
      out.write("                            <input type=\"date\" name=\"txt_fecha_orden\" id=\"txt_fecha_orden\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("\n");
      out.write("                    <!-- Fecha de Ingreso -->\n");
      out.write("                    <div class=\"form-group mb-3\">\n");
      out.write("                            <label for=\"txt_fecha_ingreso\"><b>Fecha de Ingreso:</b></label>\n");
      out.write("                            <input type=\"datetime-local\" name=\"txt_fecha_ingreso\" id=\"txt_fecha_ingreso\" class=\"form-control\" required>\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("\n");
      out.write("                    <!-- Detalles de Productos -->\n");
      out.write("                    <h5>Detalle de la Compra:</h5>\n");
      out.write("                    <div id=\"detalles_productos\">\n");
      out.write("                        <!-- Aquí se agregarán dinámicamente los productos -->\n");
      out.write("                        <div class='row mb-3 producto-row'>\n");
      out.write("                            <div class='col-md-4'>\n");
      out.write("                                <label for='id_producto'><b>Producto:</b></label>\n");
      out.write("                                <select name='id_producto[]' class='form-control' id='selectProductos' required>\n");
      out.write("                                    ");
 
                                        Marca marca = new Marca();
                                        DefaultTableModel tablaProductos = marca.leer();
                                        for (int t = 0; t < tablaProductos.getRowCount(); t++) {
                                            out.println("<option value='" + tablaProductos.getValueAt(t, 0) + "'>" + tablaProductos.getValueAt(t, 1) + "</option>");
                                        }
                                    
      out.write("\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <div class='col-md-4'>\n");
      out.write("                                <label for='cantidad'><b>Cantidad:</b></label>\n");
      out.write("                                <input type='number' name='cantidad[]' min='1' class='form-control' id='txt_cantidad' required/>\n");
      out.write("                            </div>\n");
      out.write("                            <div class='col-md-4'>\n");
      out.write("                                <label for='precio_unitario'><b>Precio Unitario:</b></label>\n");
      out.write("                                <input type='number' step='.01' name='precio_costo_unitario[]' class='form-control' id='txt_precio_unitario' required/>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Acciones -->\n");
      out.write("                    <div class='row mt-3'>\n");
      out.write("    <div class='col-md-4'>\n");
      out.write("        <button name='action' value='agregar' class='btn btn-success w-100' style=\"border-radius: 25px; transition: background-color 0.3s, transform 0.3s;\" onmouseover=\"this.style.backgroundColor='#28a745'; this.style.transform='scale(1.05)';\" onmouseout=\"this.style.backgroundColor=''; this.style.transform='scale(1)';\">\n");
      out.write("            <i class=\"bi bi-plus-circle\"></i> Agregar\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("    <div class='col-md-4'>\n");
      out.write("        <button name='action' value='actualizar' class='btn btn-warning w-100' style=\"border-radius: 25px; transition: background-color 0.3s, transform 0.3s;\" onmouseover=\"this.style.backgroundColor='#ffc107'; this.style.transform='scale(1.05)';\" onmouseout=\"this.style.backgroundColor=''; this.style.transform='scale(1)';\">\n");
      out.write("            <i class=\"bi bi-pencil\"></i> Modificar\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("    <div class='col-md-4'>\n");
      out.write("        <button name='action' value='eliminar'\n");
      out.write("                onclick='javascript:if(!confirm(\"¿Desea Eliminar?\"))return false'\n");
      out.write("                class='btn btn-danger w-100' style=\"border-radius: 25px; transition: background-color 0.3s, transform 0.3s;\" onmouseover=\"this.style.backgroundColor='#dc3545'; this.style.transform='scale(1.05)';\" onmouseout=\"this.style.backgroundColor=''; this.style.transform='scale(1)';\">\n");
      out.write("            <i class=\"bi bi-trash\"></i> Eliminar\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <div class='modal-footer'>\n");
      out.write("                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cerrar</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("                                \n");
      out.write("<div class=\"table-responsive\" style=\"max-height: 300px; overflow-y: auto;\">\n");
      out.write("    <table class=\"table table-striped table-hover\">\n");
      out.write("        <thead style=\"position: sticky; top: 0; background-color: white; z-index: 1;\">\n");
      out.write("            <tr>\n");
      out.write("                <th>ID Compra</th>\n");
      out.write("                <th>Número de Orden</th>\n");
      out.write("                <th>Proveedor</th>\n");
      out.write("                <th>Fecha de Orden</th>\n");
      out.write("                <th>Fecha de Ingreso</th>\n");
      out.write("                <th>Producto</th>\n");
      out.write("                <th>Cantidad</th>\n");
      out.write("                <th>Precio Unitario</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody id=\"tbl_compras\">\n");
      out.write("            ");

                Compras compras = new Compras();
                DefaultTableModel tablaCompras = compras.leer();
                for (int t = 0; t < tablaCompras.getRowCount(); t++) {
                    out.println("<tr data-id='" + tablaCompras.getValueAt(t, 0) + "' data-id_p='" + tablaCompras.getValueAt(t, 5) + "' data-id_producto='" + tablaCompras.getValueAt(t, 6) + "'>");
                    out.println("<td>" + tablaCompras.getValueAt(t, 0) + "</td>"); // ID Compra
                    out.println("<td>" + tablaCompras.getValueAt(t, 1) + "</td>"); // Número de Orden
                    out.println("<td>" + tablaCompras.getValueAt(t, 4) + "</td>"); // Proveedor
                    out.println("<td>" + tablaCompras.getValueAt(t, 2) + "</td>"); // Fecha de Orden
                    out.println("<td>" + tablaCompras.getValueAt(t, 3) + "</td>"); // Fecha de Ingreso
                    out.println("<td>" + tablaCompras.getValueAt(t, 7) + "</td>"); // Producto
                    out.println("<td>" + tablaCompras.getValueAt(t, 8) + "</td>"); // Cantidad
                    out.println("<td>" + tablaCompras.getValueAt(t, 9) + "</td>"); // Precio Unitario
                    
                    out.println("</tr>");
                }
            
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script>\n");
      out.write("            \n");
      out.write("                function limpiar() {    \n");
      out.write("             $(\"#txt_noc\").val('');    \n");
      out.write("             $(\"#txt_fecha_orden\").val('');    \n");
      out.write("             $(\"#txt_fecha_ingreso\").val('');    \n");
      out.write("             $(\"#txt_id_proveedor\").val(1);\n");
      out.write("         }\n");
      out.write("\n");
      out.write("         $('#tbl_compras').on('click', 'tr', function (event) {\n");
      out.write("             var target, id_compra, numeroOrden, id_proveedor, fechaOrden, fechaIngreso, producto, cantidad, precio_costo_unitario;    \n");
      out.write("             target = $(this);\n");
      out.write("\n");
      out.write("             id_compra = target.data('id'); \n");
      out.write("             numeroOrden = target.find(\"td\").eq(1).html();\n");
      out.write("             id_proveedor = target.data('id_p'); \n");
      out.write("             fechaOrden = target.find(\"td\").eq(3).html();\n");
      out.write("             fechaIngreso = target.find(\"td\").eq(4).html();\n");
      out.write("             producto = target.data('id_producto');\n");
      out.write("             cantidad = target.find(\"td\").eq(6).html();\n");
      out.write("             precio_costo_unitario = target.find(\"td\").eq(7).html();\n");
      out.write("\n");
      out.write("             $(\"#txt_id_compra\").val(id_compra);\n");
      out.write("             $(\"#txt_noc\").val(numeroOrden);\n");
      out.write("             $(\"#txt_id_proveedor\").val(id_proveedor); \n");
      out.write("             $(\"#txt_fecha_orden\").val(fechaOrden);\n");
      out.write("             $(\"#txt_fecha_ingreso\").val(fechaIngreso);\n");
      out.write("             $(\"#selectProductos\").val(producto); \n");
      out.write("             $(\"#txt_cantidad\").val(cantidad);\n");
      out.write("             $(\"#txt_precio_unitario\").val(precio_costo_unitario);\n");
      out.write("\n");
      out.write("             $(\"#modal_nueva_compra\").modal('show');\n");
      out.write("\n");
      out.write("         });\n");
      out.write("                 </script>\n");
      out.write("             </body>\n");
      out.write("         </html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
