/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-31 07:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Reportes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Generar Reportes en PDF</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\"> <!-- Fuente Roboto -->\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: 'Roboto', sans-serif;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("            margin: 0;\n");
      out.write("            background: linear-gradient(to right, #4facfe, #00f2fe); /* Gradiente de fondo */\n");
      out.write("            color: #333;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            text-align: center;\n");
      out.write("            background: #ffffff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 2rem;\n");
      out.write("            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);\n");
      out.write("            max-width: 400px;\n");
      out.write("            width: 90%;\n");
      out.write("            transition: transform 0.3s; /* Transición suave */\n");
      out.write("        }\n");
      out.write("        .container:hover {\n");
      out.write("            transform: translateY(-5px); /* Efecto de elevación */\n");
      out.write("        }\n");
      out.write("        h1 {\n");
      out.write("            font-size: 2em; /* Tamaño de fuente aumentado */\n");
      out.write("            color: #333;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1); /* Sombra del texto */\n");
      out.write("        }\n");
      out.write("        .pdf-links {\n");
      out.write("            list-style: none;\n");
      out.write("            padding: 0;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        .pdf-links li {\n");
      out.write("            margin: 1rem 0; /* Espaciado aumentado */\n");
      out.write("        }\n");
      out.write("        .pdf-links a {\n");
      out.write("            display: inline-block;\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: #ffffff;\n");
      out.write("            background-color: #007BFF;\n");
      out.write("            padding: 0.75rem 1.5rem;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            font-size: 1.1em; /* Tamaño de fuente aumentado */\n");
      out.write("            transition: background-color 0.3s ease, transform 0.2s; /* Transición suave */\n");
      out.write("        }\n");
      out.write("        .pdf-links a:hover {\n");
      out.write("            background-color: #0056b3;\n");
      out.write("            transform: scale(1.05); /* Efecto de crecimiento al pasar el mouse */\n");
      out.write("        }\n");
      out.write("        /* Estilos para pantallas pequeñas */\n");
      out.write("        @media (max-width: 600px) {\n");
      out.write("            h1 {\n");
      out.write("                font-size: 1.5em; /* Tamaño de fuente ajustado */\n");
      out.write("            }\n");
      out.write("            .pdf-links a {\n");
      out.write("                font-size: 1em; /* Tamaño de fuente ajustado */\n");
      out.write("                padding: 0.5rem 1rem; /* Espaciado ajustado */\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        function generatePDF(tipo) {\n");
      out.write("            // Redirigir a la URL del PDF\n");
      out.write("            window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pdfgenerator?tipo=' + tipo;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1>Generar Reportes en PDF</h1>\n");
      out.write("        <ul class=\"pdf-links\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"javascript:void(0);\" onclick=\"generatePDF('clientes')\">PDF de Clientes</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"javascript:void(0);\" onclick=\"generatePDF('productos')\">PDF de Productos</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"javascript:void(0);\" onclick=\"generatePDF('ventas')\">PDF de Ventas</a>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
