/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-24 23:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import modelo_clientes.ConexionBD;
import java.text.SimpleDateFormat;

public final class Clientes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("modelo_clientes.ConexionBD");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Formulario de Cliente</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: 'Roboto', sans-serif;\n");
      out.write("            background-color: #f0f0f0;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 10px;\n");
      out.write("        }\n");
      out.write("        h1, h2 {\n");
      out.write("            text-align: center;\n");
      out.write("            color: #333;\n");
      out.write("            margin: 10px 0;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            max-width: 1000px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding: 50px;\n");
      out.write("            background: #e6f7ff;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("        .formulario {\n");
      out.write("            flex: 1;\n");
      out.write("            margin-right: 50px;\n");
      out.write("            background: #ffffff;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("        form {\n");
      out.write("            display: grid;\n");
      out.write("            gap: 5px;\n");
      out.write("        }\n");
      out.write("        label {\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        input[type=\"text\"], input[type=\"email\"], input[type=\"date\"], select {\n");
      out.write("            padding: 6px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            width: 100%;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        input[type=\"submit\"] {\n");
      out.write("            background-color: #007bff;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            padding: 8px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("        input[type=\"submit\"]:hover {\n");
      out.write("            background-color: #0056b3;\n");
      out.write("        }\n");
      out.write("        .tabla-container {\n");
      out.write("            flex: 2;\n");
      out.write("            overflow-y: auto;\n");
      out.write("            max-height: 300px;\n");
      out.write("            background: #ffffff;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            border: 2px solid #007bff;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        th, td {\n");
      out.write("            padding: 8px;\n");
      out.write("            text-align: left;\n");
      out.write("            border-bottom: 1px solid #ddd;\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("        th {\n");
      out.write("            background-color: #007bff;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("        tr:hover {\n");
      out.write("            background-color: #f1f1f1;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        function seleccionarFila(index) {\n");
      out.write("            const fila = document.getElementById('cliente-data-' + index);\n");
      out.write("            const clienteData = fila.dataset;\n");
      out.write("\n");
      out.write("            document.getElementById('index').value = index;\n");
      out.write("            document.getElementById('nombre').value = clienteData.nombre;\n");
      out.write("            document.getElementById('apellidos').value = clienteData.apellidos;\n");
      out.write("            document.getElementById('nit').value = clienteData.nit;\n");
      out.write("            document.getElementById('genero').value = clienteData.genero;\n");
      out.write("            document.getElementById('telefono').value = clienteData.telefono;\n");
      out.write("            document.getElementById('correo').value = clienteData.correoElectronico;\n");
      out.write("            document.getElementById('fecha_ingreso').value = clienteData.fechaIngreso; // Se utiliza el formato correcto\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"formulario\">\n");
      out.write("        <h1>Registro de Cliente</h1>\n");
      out.write("\n");
      out.write("        ");
 
            String mensaje = (String) request.getAttribute("mensaje");
            if (mensaje != null) {
        
      out.write("\n");
      out.write("            <p style=\"color: red; text-align: center;\"><strong>");
      out.print( mensaje );
      out.write("</strong></p>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("\n");
      out.write("        <form name=\"clienteForm\" action=\"sr_clientes\" method=\"POST\">\n");
      out.write("            <input type=\"hidden\" id=\"index\" name=\"index\">\n");
      out.write("            <label for=\"nombre\">Nombre:</label>\n");
      out.write("            <input type=\"text\" id=\"nombre\" name=\"nombres\" required>\n");
      out.write("            \n");
      out.write("            <label for=\"apellidos\">Apellidos:</label>\n");
      out.write("            <input type=\"text\" id=\"apellidos\" name=\"apellidos\" required>\n");
      out.write("            \n");
      out.write("            <label for=\"nit\">NIT:</label>\n");
      out.write("            <input type=\"text\" id=\"nit\" name=\"nit\" required>\n");
      out.write("            \n");
      out.write("            <label for=\"genero\">Género:</label>\n");
      out.write("            <select id=\"genero\" name=\"genero\">\n");
      out.write("                <option value=\"1\">Masculino</option>\n");
      out.write("                <option value=\"0\">Femenino</option>\n");
      out.write("                <option value=\"2\">Otro</option>\n");
      out.write("            </select>\n");
      out.write("            \n");
      out.write("            <label for=\"telefono\">Teléfono:</label>\n");
      out.write("            <input type=\"text\" id=\"telefono\" name=\"telefono\" required>\n");
      out.write("            \n");
      out.write("            <label for=\"correo\">Correo Electrónico:</label>\n");
      out.write("            <input type=\"email\" id=\"correo\" name=\"correo_electronico\" required>\n");
      out.write("            \n");
      out.write("            <label for=\"fecha_ingreso\">Fecha de Ingreso:</label>\n");
      out.write("            <input type=\"date\" id=\"fecha_ingreso\" name=\"fecha_ingreso\" required>\n");
      out.write("            \n");
      out.write("            <input type=\"submit\" name=\"accion\" value=\"Registrar Cliente\">\n");
      out.write("            <input type=\"submit\" name=\"accion\" value=\"Modificar Cliente\">\n");
      out.write("            <input type=\"submit\" name=\"accion\" value=\"Eliminar Cliente\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"tabla-container\">\n");
      out.write("        <h2>Lista de Clientes</h2>\n");
      out.write("        <table>\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID</th>\n");
      out.write("                    <th>Nombres</th>\n");
      out.write("                    <th>Apellidos</th>\n");
      out.write("                    <th>NIT</th>\n");
      out.write("                    <th>Género</th>\n");
      out.write("                    <th>Teléfono</th>\n");
      out.write("                    <th>Correo Electrónico</th>\n");
      out.write("                    <th>Fecha de Ingreso</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                ");

                    Connection conn = null;
                    PreparedStatement stmt = null;
                    ResultSet rs = null;

                    try {
                        conn = ConexionBD.obtenerConexion();
                        String sql = "SELECT id_Cliente, nombres, apellidos, NIT, genero, telefono, correo_electronico, fecha_ingreso FROM clientes";
                        stmt = conn.prepareStatement(sql);
                        rs = stmt.executeQuery();

                        SimpleDateFormat formatoSalida = new SimpleDateFormat("yyyy-MM-dd");

                        while (rs.next()) {
                            int id = rs.getInt("id_Cliente");
                            String nombre = rs.getString("nombres");
                            String apellidos = rs.getString("apellidos");
                            String nit = rs.getString("NIT");
                            int genero = rs.getInt("genero");
                            String telefono = rs.getString("telefono");
                            String correoElectronico = rs.getString("correo_electronico");
                            java.sql.Date fechaIngresoSQL = rs.getDate("fecha_ingreso");
                            String fechaFormatoCorrecto = fechaIngresoSQL != null ? formatoSalida.format(fechaIngresoSQL) : "";

                
      out.write("\n");
      out.write("                            <tr id=\"cliente-data-");
      out.print( id );
      out.write("\" data-nombre=\"");
      out.print( nombre );
      out.write("\" data-apellidos=\"");
      out.print( apellidos );
      out.write("\" data-nit=\"");
      out.print( nit );
      out.write("\" data-genero=\"");
      out.print( genero );
      out.write("\" data-telefono=\"");
      out.print( telefono );
      out.write("\" data-correo-electronico=\"");
      out.print( correoElectronico );
      out.write("\" data-fecha-ingreso=\"");
      out.print( fechaFormatoCorrecto );
      out.write("\" onclick=\"seleccionarFila(");
      out.print( id );
      out.write(")\">\n");
      out.write("                                <td>");
      out.print( id );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( nombre );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( apellidos );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( nit );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( genero == 1 ? "Masculino" : (genero == 0 ? "Femenino" : "Otro") );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( telefono );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( correoElectronico );
      out.write("</td>\n");
      out.write("                                <td>");
      out.print( fechaFormatoCorrecto );
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                ");

                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    } finally {
                        if (rs != null) try { rs.close(); } catch (SQLException e) {}
                        if (stmt != null) try { stmt.close(); } catch (SQLException e) {}
                        if (conn != null) try { conn.close(); } catch (SQLException e) {}
                    }
                
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
