/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-24 22:59:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Login</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n");
      out.write("    <style>\n");
      out.write("        /* Estilos para el cuerpo */\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            background-color: #1a1a1a; /* Fondo oscuro */\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background-image: url('images/backgroundlogin.jpg');\n");
      out.write("            background-size: cover;\n");
      out.write("            background-position: center; \n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /* Estilos para el contenedor del formulario */\n");
      out.write("        .login-container {\n");
      out.write("            background-color: rgba(0, 0, 0, 0.7); /* Contenedor oscuro */\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.5); /* Sombra más marcada */\n");
      out.write("            padding: 30px;\n");
      out.write("            width: 300px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilos para el título */\n");
      out.write("        .login-container h2 {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            color: #00A7FF; /* Tono azul */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilos para los campos de entrada */\n");
      out.write("        .login-container input[type=\"text\"],\n");
      out.write("        .login-container input[type=\"password\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            margin: 10px 0;\n");
      out.write("            border: 1px solid #007bff; /* Borde azul */\n");
      out.write("            border-radius: 5px;\n");
      out.write("            background-color: #333; /* Fondo de entrada oscuro */\n");
      out.write("            color: #fff; /* Texto blanco */\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilos para el botón de login */\n");
      out.write("        .login-container input[type=\"submit\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            background-color: #00A7FF; /* Botón azul */\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            color: #ffffff;\n");
      out.write("            font-weight: bold;\n");
      out.write("            cursor: pointer;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-container input[type=\"submit\"]:hover {\n");
      out.write("            background-color: #0280C4; /* Hover más oscuro */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilos para el enlace */\n");
      out.write("        .login-container a {\n");
      out.write("            display: block;\n");
      out.write("            margin-top: 15px;\n");
      out.write("            color: #00A7FF; /* Enlace azul */\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-container a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilos para el mensaje de error */\n");
      out.write("        .error-message {\n");
      out.write("            color: red;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"login-container\">\n");
      out.write("        <h2>Inicio de sesión</h2>\n");
      out.write("        <form action=\"LoginServlet\" method=\"post\">\n");
      out.write("            <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Usuario\" required>\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Contraseña\" required>\n");
      out.write("            <input type=\"submit\" value=\"Ingresar\">\n");
      out.write("        </form>\n");
      out.write("        <a href=\"registro_usuario.jsp\">Registrarse</a>\n");
      out.write("\n");
      out.write("        <!-- Mensaje de error -->\n");
      out.write("        <div id=\"error-message\" class=\"error-message\">\n");
      out.write("            <!-- Aquí se insertará el mensaje de error si hay un error -->\n");
      out.write("            <script>\n");
      out.write("                // Obtener el parámetro 'error' de la URL\n");
      out.write("                const urlParams = new URLSearchParams(window.location.search);\n");
      out.write("                const error = urlParams.get('error');\n");
      out.write("\n");
      out.write("                // Si hay un error, mostrar el mensaje correspondiente\n");
      out.write("                if (error) {\n");
      out.write("                    let errorMessage = document.getElementById('error-message');\n");
      out.write("                    if (error === '1') {\n");
      out.write("                        errorMessage.textContent = 'Usuario o contraseña incorrectos. Intente de nuevo.';\n");
      out.write("                    } else if (error === '2') {\n");
      out.write("                        errorMessage.textContent = 'Error de conexión a la base de datos. Intente más tarde.';\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
