/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-25 01:00:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class menu_00202_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Menú Dinámico</title>\n");
      out.write("    <style>\n");
      out.write("        nav ul {\n");
      out.write("            list-style-type: none;\n");
      out.write("            padding: 0;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav ul li {\n");
      out.write("            margin: 5px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav ul ul {\n");
      out.write("            margin-left: 20px; /* Submenús con sangría */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: white;\n");
      out.write("            background-color: rgba(0, 0, 0, 0.6);\n");
      out.write("            padding: 10px 15px;\n");
      out.write("            display: block;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            transition: background-color 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav a:hover {\n");
      out.write("            background-color: rgba(255, 255, 255, 0.5);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <nav>\n");
      out.write("        <ul>\n");
      out.write("            ");

                Connection con = null;
                Statement stmt = null;
                ResultSet rs = null;

                try {
                    // Conexión a la base de datos
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_tiendaa", "root", "");  // Cambia estos datos según tu configuración
                    stmt = con.createStatement();

                    // Consulta para obtener los menús principales (aquellos con parent_id NULL)
                    String query = "SELECT * FROM menus WHERE parent_id IS NULL";
                    rs = stmt.executeQuery(query);

                    // Función para mostrar submenús directamente en el código JSP
                    while (rs.next()) {
                        String nombre = rs.getString("name");
                        String url = rs.getString("url");
                        int id = rs.getInt("id");

                        if (url != null) {
                            // Si el menú tiene URL, lo mostramos como enlace
                            out.println("<li><a href='" + url + "' target='content-frame'>" + nombre + "</a>");
                        } else {
                            // Si no tiene URL, es un menú sin enlace
                            out.println("<li>" + nombre);
                        }

                        // Consulta para submenús
                        Statement stmtSub = con.createStatement();
                        ResultSet rsSub = stmtSub.executeQuery("SELECT * FROM menus WHERE parent_id = " + id);

                        if (rsSub.next()) {
                            out.println("<ul>");  // Inicia la lista de submenús
                            do {
                                String subNombre = rsSub.getString("name");
                                String subUrl = rsSub.getString("url");
                                int subId = rsSub.getInt("id");

                                if (subUrl != null) {
                                    out.println("<li><a href='" + subUrl + "' target='content-frame'>" + subNombre + "</a>");
                                } else {
                                    out.println("<li>" + subNombre);
                                }

                                // Mostrar sub-submenús
                                Statement stmtSub2 = con.createStatement();
                                ResultSet rsSub2 = stmtSub2.executeQuery("SELECT * FROM menus WHERE parent_id = " + subId);

                                if (rsSub2.next()) {
                                    out.println("<ul>");  // Inicia la lista de sub-submenús
                                    do {
                                        String subSubNombre = rsSub2.getString("name");
                                        String subSubUrl = rsSub2.getString("url");

                                        if (subSubUrl != null) {
                                            out.println("<li><a href='" + subSubUrl + "' target='content-frame'>" + subSubNombre + "</a></li>");
                                        } else {
                                            out.println("<li>" + subSubNombre + "</li>");
                                        }

                                    } while (rsSub2.next());
                                    out.println("</ul>");  // Cierra la lista de sub-submenús
                                }

                                rsSub2.close();
                                stmtSub2.close();

                                out.println("</li>");
                            } while (rsSub.next());
                            out.println("</ul>");  // Cierra la lista de submenús
                        }

                        rsSub.close();
                        stmtSub.close();

                        out.println("</li>");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    if (rs != null) rs.close();
                    if (stmt != null) stmt.close();
                    if (con != null) con.close();
                }
            
      out.write("\n");
      out.write("        </ul>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <iframe id=\"content-frame\" name=\"content-frame\" style=\"width: 100%; height: calc(100vh - 50px); border: none;\"></iframe>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
