/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-02 01:27:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import modelo_marcas.marcas;
import modelo_marcas.Marca;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;

public final class Productos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("modelo_marcas.Marca");
    _jspx_imports_classes.add("javax.swing.table.DefaultTableModel");
    _jspx_imports_classes.add("modelo_marcas.marcas");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>  \n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <title>Productos</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h1 style=\"text-align: center;\">Registro de Productos</h1>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <form action=\"sr_producto\" method=\"post\" class=\"form-group\" enctype=\"multipart/form-data\">\n");
      out.write("            <label for=\"lbl_id\"><b>ID:</b></label>\n");
      out.write("            <input type=\"text\" name=\"txt_id\" id=\"txt_id\" class=\"form-control\" value=\"0\" readonly>\n");
      out.write("\n");
      out.write("            <label for=\"lbl_producto\"><b>Producto:</b></label>\n");
      out.write("            <input type=\"text\" name=\"txt_producto\" id=\"txt_producto\" class=\"form-control\" placeholder=\"Ejemplo: Producto\" required>\n");
      out.write("\n");
      out.write("            <label for=\"lbl_marca\"><b>Marca:</b></label>\n");
      out.write("            <select name=\"drop_marca\" id=\"drop_marca\" class=\"form-control\"> \n");
      out.write("                ");
 
                marcas marcas = new marcas();
                HashMap<String, String> drop = marcas.drop_Marca();
                for(String i: drop.keySet()){
                    out.println("<option value='" + i + "'> "+drop.get(i)+" </option>");
                }
                
      out.write("\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <label for=\"lbl_descripcion\"><b>Descripcion:</b></label>\n");
      out.write("            <input type=\"text\" name=\"txt_descripcion\" id=\"txt_descripcion\" class=\"form-control\" placeholder=\"Ejemplo: Descripcion\" required>\n");
      out.write("\n");
      out.write("            <label for=\"lbl_imagen\"><b>Imagen:</b></label>          \n");
      out.write("            <input type=\"file\" name=\"txt_imagen\" id=\"txt_imagen\" class=\"form-control\" accept=\"image/*\" onchange=\"previewImage()\">\n");
      out.write("            <img id=\"img_preview\" src=\"#\" alt=\"Vista previa\" style=\"display: none; width: 100px; height: auto; margin-top: 20px;\"/>\n");
      out.write("            \n");
      out.write("            <!-- Botón para descargar la imagen -->\n");
      out.write("            <button type=\"button\" id=\"btn_descargar\" onclick=\"descargarImagen()\" class=\"btn btn-info\" style=\"margin-top: 10px; display: none;\">Descargar</button>\n");
      out.write("\n");
      out.write("            <input type=\"hidden\" name=\"current_image_path\" id=\"current_image_path\">\n");
      out.write("             \n");
      out.write("            <br></br> \n");
      out.write("            <label for=\"lbl_precio_costo\"><b>Precio Costo:</b></label>\n");
      out.write("            <input type=\"number\" name=\"txt_precio_costo\" id=\"txt_precio_costo\" class=\"form-control\" placeholder=\"Ejemplo: 500.00\" required>\n");
      out.write("\n");
      out.write("            <label for=\"lbl_precio_venta\"><b>Precio Venta:</b></label>\n");
      out.write("            <input type=\"number\" name=\"txt_precio_venta\" id=\"txt_precio_venta\" class=\"form-control\" placeholder=\"Ejemplo: 650.00\" required>\n");
      out.write("\n");
      out.write("            <label for=\"lbl_existencia\"><b>Existencia:</b></label>\n");
      out.write("            <input type=\"number\" name=\"txt_existencia\" id=\"txt_existencia\" class=\"form-control\" required>\n");
      out.write("\n");
      out.write("            <label for=\"lbl_fecha_ingreso\"><b>Fecha Ingreso:</b></label>\n");
      out.write("            <input type=\"datetime-local\" name=\"txt_fecha_ingreso\" id=\"txt_fecha_ingreso\" class=\"form-control\" required>\n");
      out.write("            \n");
      out.write("            <br>\n");
      out.write("            <button type=\"submit\" name=\"btn_agregar\" id=\"btn_agregar\" value=\"agregar\" class=\"btn btn-primary\">Agregar</button>\n");
      out.write("            <button type=\"submit\" name=\"btn_modificar\" id=\"btn_modificar\" value=\"modificar\" class=\"btn btn-success\">Modificar</button>\n");
      out.write("            <button type=\"submit\" name=\"btn_eliminar\" id=\"btn_eliminar\" value=\"eliminar\" class=\"btn btn-warning\">Eliminar</button>\n");
      out.write("            <button type=\"button\" onclick=\"limpiarPantalla()\" class=\"btn btn-secondary\">Limpiar</button>\n");
      out.write("        </form>\n");
      out.write("    </div> \n");
      out.write("\n");
      out.write("    <!-- Tabla de productos -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <table class=\"table table-striped\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>Producto</th>\n");
      out.write("                    <th>Descripción</th>\n");
      out.write("                    <th>Imagen</th>\n");
      out.write("                    <th>Precio Costo</th>\n");
      out.write("                    <th>Precio Venta</th>\n");
      out.write("                    <th>Existencia</th>\n");
      out.write("                    <th>Fecha Ingreso</th>\n");
      out.write("                    <th>Marca</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody id=\"tbl_productos\">\n");
      out.write("                ");

                Marca marca = new Marca();
                DefaultTableModel tabla = marca.leer();
                for (int t = 0; t < tabla.getRowCount(); t++) {
                    out.println("<tr data-id='" + tabla.getValueAt(t, 0) + "' data-id_Marca='" + tabla.getValueAt(t, 2) + "'>");
                    out.println("<td>" + tabla.getValueAt(t, 1) + "</td>"); 
                    out.println("<td>" + tabla.getValueAt(t, 3) + "</td>"); 
                    out.println("<td><img src='" + tabla.getValueAt(t, 4) + "' alt='Imagen' style='width: 100px; height: auto;'/></td>"); // Imagen
                    out.println("<td>" + tabla.getValueAt(t, 5) + "</td>"); 
                    out.println("<td>" + tabla.getValueAt(t, 6) + "</td>"); 
                    out.println("<td>" + tabla.getValueAt(t, 7) + "</td>"); 
                    out.println("<td>" + tabla.getValueAt(t, 8) + "</td>"); 
                    out.println("<td>" + tabla.getValueAt(t, 9) + "</td>"); 
                    out.println("</tr>");
                }
                
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div> \n");
      out.write("            \n");
      out.write("            \n");
      out.write("\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function previewImage() {\n");
      out.write("            var file = document.getElementById(\"txt_imagen\").files[0];\n");
      out.write("            var reader = new FileReader();\n");
      out.write("            reader.onload = function(e) {\n");
      out.write("                document.getElementById(\"img_preview\").src = e.target.result;\n");
      out.write("                document.getElementById(\"img_preview\").style.display = \"block\";\n");
      out.write("                document.getElementById(\"btn_descargar\").style.display = \"inline\"; // Muestra el botón de descarga\n");
      out.write("            };\n");
      out.write("            reader.readAsDataURL(file);\n");
      out.write("        }\n");
      out.write("         \n");
      out.write("        // Función para descargar la imagen\n");
      out.write("        function descargarImagen() {\n");
      out.write("            var imgSrc = document.getElementById(\"img_preview\").src;\n");
      out.write("            if (imgSrc !== \"#\") {\n");
      out.write("                var link = document.createElement(\"a\");\n");
      out.write("                link.href = imgSrc;\n");
      out.write("                link.download = \"imagen_producto.jpg\"; // Nombre predeterminado para el archivo\n");
      out.write("                document.body.appendChild(link);\n");
      out.write("                link.click();\n");
      out.write("                document.body.removeChild(link);\n");
      out.write("            } else {\n");
      out.write("                alert(\"No hay imagen seleccionada para descargar.\");\n");
      out.write("            } \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        $('#tbl_productos').on('click', 'tr', function() { \n");
      out.write("    var id = $(this).data('id');\n");
      out.write("    var id_Marca = $(this).data('id_marca'); \n");
      out.write("    var producto = $(this).find(\"td\").eq(0).html();\n");
      out.write("    var descripcion = $(this).find(\"td\").eq(1).html();\n");
      out.write("    var imagen = $(this).find(\"td\").eq(2).find(\"img\").attr(\"src\");\n");
      out.write("    var precio_costo = $(this).find(\"td\").eq(3).html();\n");
      out.write("    var precio_venta = $(this).find(\"td\").eq(4).html();\n");
      out.write("    var existencia = $(this).find(\"td\").eq(5).html();\n");
      out.write("    var fecha_ingreso = $(this).find(\"td\").eq(6).html();\n");
      out.write("\n");
      out.write("    $('#txt_id').val(id);\n");
      out.write("    $('#drop_marca').val(id_Marca);\n");
      out.write("    $('#txt_producto').val(producto);\n");
      out.write("    $('#txt_descripcion').val(descripcion);\n");
      out.write("    $('#current_image_path').val(imagen); // Guardar la ruta de la imagen\n");
      out.write("    $('#img_preview').attr(\"src\", imagen).show(); // Mostrar la vista previa\n");
      out.write("    $('#txt_precio_costo').val(precio_costo);\n");
      out.write("    $('#txt_precio_venta').val(precio_venta);\n");
      out.write("    $('#txt_existencia').val(existencia);\n");
      out.write("    $('#txt_fecha_ingreso').val(fecha_ingreso);\n");
      out.write("    $('#btn_descargar').show(); // Mostrar el botón de descarga\n");
      out.write("});\n");
      out.write("\n");
      out.write("        function limpiarPantalla() {\n");
      out.write("            $('#txt_id').val(0);\n");
      out.write("            $('#drop_marca').val(\"\");\n");
      out.write("            $('#txt_producto').val(\"\");\n");
      out.write("            $('#txt_descripcion').val(\"\");\n");
      out.write("            $('#txt_imagen').val(\"\");\n");
      out.write("            $('#img_preview').hide();\n");
      out.write("            $('#txt_precio_costo').val(\"\");\n");
      out.write("            $('#txt_precio_venta').val(\"\");\n");
      out.write("            $('#txt_existencia').val(\"\");\n");
      out.write("            $('#txt_fecha_ingreso').val(\"\");\n");
      out.write("            $('#btn_descargar').hide(); // Oculta el botón de descarga\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
